name: Compose Validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: |
          API_SERVER_KEY=0123456789abcdef docker compose config --quiet
